name: Report a bug
description: Something is not working? Report a bug
body:

  - type: textarea
    id: context
    attributes:
      label: Context
      description: >-
        This field is optional. You may provide additional context for the bug
        you want to report, helping us to understand what you are working on and
        what you are trying to achieve. If the context is not relevant, you can
        leave this field empty.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#context)

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: >-
        Please give a detailed description of the bug. Explain where Material
        for MkDocs does not behave as you would expect it to. Be as specific as
        possible. If you have found a workaround or a fix for the problem,
        please let us maintainers (and all other users) know.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#bug-description)
    validations:
      required: true

  - type: textarea
    id: related-links
    attributes:
      label: Related links
      description: >-
        Please list all links to the sections of
        [our documentation](https://squidfunk.github.io/mkdocs-material/) that
        are relevant to the bug in order to show that you have consulted and
        thoroughly read it. Additionally, list links to possibly related open
        and closed [issues](https://github.com/squidfunk/mkdocs-material/issues)
        and [discussions](https://github.com/squidfunk/mkdocs-material/discussions)
        you encountered when searching our issue tracker.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#related-links)
      value: |-
        - [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
        -
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: >-
        Please create a __.zip file__ with a __minimal reproduction__ for the
        bug. First, read our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/)
        that explains the necessary steps, then use the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/) (mandatory) to create a self-contained
        .zip file with the reproduction. We reserve the right to close issues
        without .zip files.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction)
      placeholder: |-
        Drag and drop the .zip file with the minimal reproduction here.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Please provide a detailed list of instructions, guiding us maintainers
        through the required steps, helping us to recreate the problem using the
        minimal reproduction you provided. Be as specific as possible and as
        verbose as necessary – try not to leave anything out.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#steps-to-reproduce)
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: >-
        This field is optional. If the bug only happens in __specific browsers__,
        please select them from the dropdown below. If your browser is not
        listed or the version is relevant, you may select _Other_ and provide
        more details in the field above.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#browser)
      multiple: true
      options:
        - Chrome
        - Safari
        - Edge
        - Firefox
        - Opera
        - Other

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you are not sure what a specific requirement means, follow the link
        to learn about it and understand why it is necessary before ticking the
        box. This will save the maintainers and you valuable time.
      options:
        - label: >-
            I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
          required: true
        - label: >-
            I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/),
            and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues)
            and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
          required: true
        - label: >-
            I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations)
            before submitting this bug report.
          required: true
        - label: >-
            I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
          required: true
